### ISSUE TITLE
Running Jenkins on Docker and using docker-plugin

### ISSUE THREAD

**Issue by fcoelho** [jenkinsci/docker-plugin#206]
I'm running Jenkins on Docker using [the official image](https://registry.hub.docker.com/_/jenkins/) from the Docker Hub, and I'm trying to use the `docker-plugin` to connect to containers running on the same Docker host as the Jenkins server.

Since the `docker-plugin` can't yet connect to a unix socket, I'm running `socat` on the Jenkins container to proxy a local TCP socket to the volume-mounted `/var/run/docker.sock`. That means the Jenkins server connects to `localhost:4243`, but the real Docker host is on, say, `10.0.0.5`.

When a new container is created, port 22 is exposed to `0.0.0.0:48349` (some random port), to which Jenkins then tries to connect. But the problem is that Jenkins is trying to connect to `localhost:48349`, and obviously failing since `localhost` for the Jenkins server is a different network than `localhost` for the Docker server.

I'd like to achieve two things, if possible:
- Have Jenkins create the containers but _not_ expose any ports outside of the container
- Have Jenkins connect to the container's IP directly, not through `localhost` or other settings, i.e., I want Jenkins to connect to (for example) `172.17.0.20:22` (which is why I don't want it to expose any ports - there's simply no need for it in my case)

Is this possible with any current version of the docker-plugin? I tried fiddling with a few settings but it doesn't seem like it is possible to ignore [the exposed port](https://github.com/jenkinsci/docker-plugin/blob/master/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplate.java#L296) setting and https://github.com/jenkinsci/docker-plugin/pull/200 deals with a similar though different issue.

**Comment by KostyaSha** [comment]
Next time please provide installed versions https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue#Howtoreportanissue-WhatinformationtoprovideforEnvironmentandDescription
also this should be fixed in master, feel free to try this hpi https://jenkins.ci.cloudbees.com/job/plugins/job/docker-plugin/226/com.nirima$docker-plugin/

**Comment by fcoelho** [comment]
Sorry about that.

Jenkins 1.596.2
Docker-plugin: tried building from source yesterday and used the one from the build server today
Docker Server version: 1.4.1
Docker Server API version: 1.16

The hpi you linked to doesn't fix the issue, it is still trying to connect to `localhost` and exposing port 22 to 0.0.0.0.

Jenkins logs:
```
[04/17/15 16:51:42] [SSH] Opening SSH connection to localhost:49178.
Connection refused
SSH Connection failed with IOException: "Connection refused".
java.io.IOException: There was a problem while connecting to localhost:49178
	at com.trilead.ssh2.Connection.connect(Connection.java:818)
	at com.trilead.ssh2.Connection.connect(Connection.java:687)
	at com.trilead.ssh2.Connection.connect(Connection.java:587)
	at hudson.plugins.sshslaves.SSHLauncher.openConnection(SSHLauncher.java:1146)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:701)
	at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:696)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.trilead.ssh2.transport.TransportManager.establishConnection(TransportManager.java:354)
	at com.trilead.ssh2.transport.TransportManager.initialize(TransportManager.java:467)
	at com.trilead.ssh2.Connection.connect(Connection.java:758)
	... 9 more
[04/17/15 16:51:42] Launch failed - cleaning up connection
[04/17/15 16:51:42] [SSH] Connection closed.
```

Docker inspect subset on the created container:
```
    "NetworkSettings": {
        "Bridge": "docker0",
        "Gateway": "172.17.42.1",
        "IPAddress": "172.17.0.101",
        "IPPrefixLen": 16,
        "MacAddress": "02:42:ac:11:00:65",
        "PortMapping": null,
        "Ports": {
            "22/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "49178"
                }
            ]
        }
    },
```

**Comment by KostyaSha** [comment]
What about firewall?

**Comment by KostyaSha** [comment]
@srwalter could you check?

**Comment by fcoelho** [comment]
@KostyaSha no issues with the firewall, if I exec into the jenkins container I'm able to connect to each slave container:

```
[user@host ~]$ sudo docker exec -it jenkins_container bash
root@989e6ef3fa5e:/# ssh jenkins@172.17.0.106
The authenticity of host '172.17.0.106 (172.17.0.106)' can't be established.
ECDSA key fingerprint is 70:9d:ae:ad:22:0c:4c:b3:ef:bf:71:e5:f5:88:95:60.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '172.17.0.106' (ECDSA) to the list of known hosts.
jenkins@172.17.0.106's password: 
Linux minas-morgul 3.16.5-gentoo #1 SMP Fri Oct 24 15:50:40 PDT 2014 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Apr 16 15:36:13 2015 from localhost
jenkins@64d698d2cc37:~$ 

```

**Comment by davewv31** [comment]
@fcoelho 
Hi there. I'm running in a similar situation to you, but I have things working. Well, mostly working. Odd problem with spawning a container as a slave, failing, then spawning another and having it work. 

Jenkins: 1.596.2
Docker Plugin: 0.9-beta1
Docker Version: 1.6 (may have had it working on 1.4.x)

Jenkins official docker image with some slight customization, running in a docker container. Started with a custom Ansible script.
Docker started with Ansible via the angstwad.docker_ubuntu role and custom vars. I have the docker_opts set up to allow tcp. This seems to create an /etc/default/docker file on the docker host machine that shows 
````sh
~$more /etc/default/docker
DOCKER_OPTS="-H unix:// -H tcp://0.0.0.0:2375"
````

Docker Cloud Configuration
````sh
Name: dockerlocal
Docker URL: http://172.17.42.1:2375
````

I still think your problem is valid and could use a solution, but this may allow you to abandon localhost and get things working.

**Comment by KostyaSha** [comment]
>That means the Jenkins server connects to localhost:4243, but the real Docker host is on, say, 10.0.0.5.
This looks like a really weird use case. You can try to work with hostname or proxy 4243.

**Comment by looztra** [comment]
That's not a weird use case. The plugin currently asserts that it can connect to the slave by using the ip of what it is given as the docker host (guessed using from the *docker url* settings) + using the exported ssh port on the same docker host.

I'm running exactly the same use case as @fcoelho:

* a docker host
* a jenkins master that is a container on the docker host
* because we don't want to open the docker daemon port to the world (unlike suggested in the plugin docs) we use a "trick": we use the *socat* binary to expose the docker socket as a port of the jenkins master (or of a dedicated container in my case). So the jenkins master/socat container bind mounts the /var/run/docker.sock that is exported as a tcp port in the ip/namespace of this container.
* the *docker_url* settings of the plugin is then set to something like *http://${docker-socat-container-ip}:2375*

the current behaviour of the plugin is to try to connect to the ${docker_url.host}:${port_from_docker_inspect}...that cannot work in our setup because the ${docker_url.host} is not the really host/ip that is exporting the public ip (the *inspected* one).

The workaround could be to provide an option that would allow to use directly the *ip:port* of the slave in the docker bridge ip namespace.

For the record:
 * I'm running jenkins 1.609.2 + docker plugin version 0.11.0
My setup uses docker-compose + a data container:
```yaml
docker:
  image: rancher/socat-docker
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
jmaster:
  image: looztra/c7-jenkins-master
  volumes_from:
  - datamaster
  ports:
  - 8080:8080
  links:
  - docker
```

**Comment by KostyaSha** [comment]
Seems it can be bypassed with JNLP slaves ;) I will try reorder priorities and release JNLP launcher as experimental after #300 and #298

**Comment by jglick** [comment]
@ndeloof and @cyrille-leclerc and @michaelneale might be interested in this request, relating to running the master in a container on the same host as the slave agents. Ideally this would work transparently under Swarm.

I am also interested in running build steps inside job-specific containers (via `docker-custom-build-environment` or `docker-workflow`) with the same host as the slave agent (running inside a generic container), but that is a different concern which probably does not need special support from the Docker plugin.

**Comment by ndeloof** [comment]
@jglick I'm considering something equivalent (iiuc), with a jenkins-slave specific image to provide remoting capabilities and slave rootdir as a volume, then have docker-custom-build-environment / docker-workflow run containers with --volume-from so they share workspace.

**Comment by michaelneale** [comment]
@jglick @ndeloof yes I think this is a good idea. It would be nice if docker-commons could have optional support for docker sockets - in which case bind mounting in would be far simpler. 

Could all this be demonstrated with a docker-compose.yml so people get an out-of-box experience? (it probably could with bind mounting the socket, but if a proxy is needed, probably not).

**Comment by smiller171** [comment]
Has anyone gotten this working? Perhaps using JNLP sockets? 

I have the slaves starting, but not connecting to them

**Comment by KostyaSha** [comment]
Works fine for me.

**Comment by smiller171** [comment]
@KostyaSha Could Are there any details of your implementation documented somewhere? I feel like it's something I'm doing, but I can't find a documented answer. This thread is the best I have found so far.

**Comment by avblink** [comment]
Can someone please provide a working docker-compose.yml

Thank you

**Comment by KostyaSha** [comment]
Just use api access without sockets, then everything should work fine.

**Comment by avblink** [comment]
Here is my setup:
host is running docker service on docker.sock and TCP port 4243.
If I navigate to http://127.0.0.1:4243/containers/json I see correct json output.

I spawn Jenkins container from the host and share docker.sock volume.
Within Jenkins container I install docker client.

Jenkins has there plugins installed:
authentication-tokens:1.2
docker-build-step:1.33
docker-commons:1.2

To set up docker-build-step plugin I navigate to Jenkins config and set RESP API URI to 127.0.0.1:4243. When clicking on TEST button it returns error.

Am I missing a step? Trying to set up a good behat testing framework and get stuck at this point.

Thank you for your help/advice in advance.

Alex

**Comment by smiller171** [comment]
@avblink I got it running by talking out to the DNS address of the host instead of trying to talk up through Docker's networking stack

**Comment by machzqcq** [comment]
@avblink It works as @smiller171 said with DNS address of the host. However containers spun up on docker-machine cannot talk to the DNS address too. The only way this works so far for me is on a flat network. Any containers (inside VM's) or more levels deeper - I run into "## shaded.org.apache.http.client" exception when "Test" is clicked on the configuration section for docker in Jenkins Configuration page.

The reason I ask if anyone has a solution and got it working in a complete docker-machine environment please ? It would really help to have a complete sandbox environment. In fact I read the below posts too and followed but no luck  

https://github.com/jpetazzo/dind  
http://container-solutions.com/running-docker-in-jenkins-in-docker/

**Comment by Ian-Rossi-aimtheory** [comment]
@smiller171 Would you mind saying here where in the Jenkins config you indicated the DNS address of the host? I am running the Jenkins master in a Docker container where the Jenkins slaves are "sibling" containers on the same host. So when it does an SSH to them, it needs to SSH to Docker host and not the IP address of the Jenkins master. But the "Configure System" page under "Manage Jenkins" doesn't appear to have a place where you can indicate the host to connect to, only the port. 

If I choose the JNLP launcher, there is a "Tunnel Through" field where I can enter the Docker hostname, but not for the Docker SSH launcher.

So, if you can detail how you were able to 'talk out' to the DNS of the Docker host, I would really appreciate it. Thanks!

**Comment by ndeloof** [comment]
closing as obsolete

**Comment by devopskartik** [comment]
My Scenario :
- Centos7 inside Virtual box on Windows server
- Jenkins runs as docker container 
I have resolved the issue by opening the port of Docker API through firewall.
Working find Under NAT.
