### ISSUE TITLE
0.9.0 beta2 testing

### ISSUE THREAD

**Issue by KostyaSha** [jenkinsci/docker-plugin#210]
New build was uploaded to http://jenkins-ci.org/content/experimental-plugins-update-center  (if it not available, then download directly http://maven.jenkins-ci.org:8081/content/repositories/releases/com/nirima/docker-plugin/0.9.0-beta2/docker-plugin-0.9.0-beta2.hpi ).
Please try and provide feedback.
If you found some issue (not all still resolved), please search through existed in this Issues or PRs. 
And only then open new, in new issue please provide the next information https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue#Howtoreportanissue-WhatinformationtoprovideforEnvironmentandDescription

**Comment by KostyaSha** [comment]
:angry: help files not shown, fixed in master, instead of beta2, this hpi can be picked https://jenkins.ci.cloudbees.com/job/plugins/job/docker-plugin/251/com.nirima$docker-plugin/

**Comment by KostyaSha** [comment]
This version better that 0.8. People contiue reporting ancient 0.8.  Will do 0.9.0-rc1 release that will be available in main UC.

**Comment by KostyaSha** [comment]
Uploaded: http://maven.jenkins-ci.org:8081/content/repositories/releases/com/nirima/docker-plugin/0.9.0-rc1/docker-plugin-0.9.0-rc1.hpi

**Comment by KostyaSha** [comment]
Now all issues will be general and not 'beta check'

**Comment by diranged** [comment]
So just a heads up, this changed the issue in #186, but did not resolve it completely.
