### ISSUE TITLE
Optimizing Node provisioning strategy

### ISSUE THREAD

**Issue by Jochen-A-Fuerbacher** [jenkinsci/docker-plugin#427]
Hello,

I discovered two issues.

When there are items in the queue and no executors are available,
- it can take some time (up to some minutes) until new container agents get started. But sometimes new container agents get started immediately.
- sometimes more container agents get started than needed. E.g. No free executors available, 4 items in the queue. Then sometimes 5 or more container agents get started.

I'm not sure if this is an issue of Docker Plugin or the Jenkins NodeProvisioner Strategy.

Thank you!

**Comment by jommgoncalves** [comment]
+1

**Comment by farahfa** [comment]
Yes, this is something that I keep on getting complaints on.

**Comment by KostyaSha** [comment]
Feel free to try https://github.com/KostyaSha/yet-another-docker-plugin/ , implemented and fixed long time ago. 

Seems need unsubscribe from this repo to stop commenting this plugin.

**Comment by Jochen-A-Fuerbacher** [comment]
Thank you, @KostyaSha.
I looked at Yet Another Docker Plugin (disabled Docker Plugin) and the behaviour is unfortunately exactly the same.

**Comment by KostyaSha** [comment]
it can't be the same, please open separate issue and i will help understand what is hapenning.

**Comment by Jochen-A-Fuerbacher** [comment]
Done [https://github.com/KostyaSha/yet-another-docker-plugin/issues/74](url).

**Comment by magnayn** [comment]
Whilst it's possible that it's taking some time to provision and/or connect to spawned slaves, I think it's mostly a Jenkins issue.

The Jenkins cloud API (which the plugin implements) isn't responsible for scheduling the work - it merely does the docker-specific bits when asked.

**Comment by KostyaSha** [comment]
@eaglerainbow i investigated all this things long time ago there are also differences between core versions.

**Comment by antweiss** [comment]
@KostyaSha I took the inspiration from your YAD ProvisioningStrategy implementation for the Nomad Plugin and it works well - new nodes are getting provisioned ASAP. thank you :)

**Comment by KostyaSha** [comment]
@antweiss you are welcome. Still don't understand how people can use and waste time on this docker-plugin.

**Comment by ndeloof** [comment]
fixed on 0.17
